In [1]:
import numpy as np

Creating Arrays from Python Lists

In [2]:
array_from_list = np.array(["hello","how","are","you?"])
array_from_list

array(['hello', 'how', 'are', 'you?'], dtype='<U5')

In [3]:
#Set the data type of an array with dtype
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

Creating Arrays from Scratch

In [22]:
#A bunch of zeroes, as much as you want
np.zeros(100, dtype=float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
#A bunch of zeroes, as much as you want
np.ones((10,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [27]:
#A bunch of whatever you want
np.full((3,3),"!!!!!!!!!!!!!!!")

array([['!!!!!!!!!!!!!!!', '!!!!!!!!!!!!!!!', '!!!!!!!!!!!!!!!'],
       ['!!!!!!!!!!!!!!!', '!!!!!!!!!!!!!!!', '!!!!!!!!!!!!!!!'],
       ['!!!!!!!!!!!!!!!', '!!!!!!!!!!!!!!!', '!!!!!!!!!!!!!!!']],
      dtype='<U15')

In [6]:
#Create an array with numbers from one number to another with specified steps
np.arange(69,420,7)

array([ 69,  76,  83,  90,  97, 104, 111, 118, 125, 132, 139, 146, 153,
       160, 167, 174, 181, 188, 195, 202, 209, 216, 223, 230, 237, 244,
       251, 258, 265, 272, 279, 286, 293, 300, 307, 314, 321, 328, 335,
       342, 349, 356, 363, 370, 377, 384, 391, 398, 405, 412, 419])

In [9]:
#Create an array with numbers from a certain range that are evenly spaced into specified numbers
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [19]:
#Uniformly distributed random numbers
np.random.random(4)

array([0.81330043, 0.06543981, 0.17136477, 0.27248551])

In [16]:
#Random integers in a given range
np.random.randint(13,18,10)

array([13, 14, 13, 16, 13, 14, 16, 15, 13, 17])

In [20]:
#Numpy identity matrix 
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Numpy Array Attributes

In [30]:
#Example Array
array_for_attributes = np.full((2,3,4), "whatthewhat")
array_for_attributes

array([[['whatthewhat', 'whatthewhat', 'whatthewhat', 'whatthewhat'],
        ['whatthewhat', 'whatthewhat', 'whatthewhat', 'whatthewhat'],
        ['whatthewhat', 'whatthewhat', 'whatthewhat', 'whatthewhat']],

       [['whatthewhat', 'whatthewhat', 'whatthewhat', 'whatthewhat'],
        ['whatthewhat', 'whatthewhat', 'whatthewhat', 'whatthewhat'],
        ['whatthewhat', 'whatthewhat', 'whatthewhat', 'whatthewhat']]],
      dtype='<U11')

In [31]:
#Number of dimensions
array_for_attributes.ndim

3

In [34]:
#Shape
array_for_attributes.shape

(2, 3, 4)

In [35]:
#Size
array_for_attributes.size

24

In [36]:
#type of array
array_for_attributes.dtype

dtype('<U11')

Array Indexing

In [37]:
#Example 1D array
1d_example = np.array(["what", "am", "doing", "over", "here", "and", "not", "over", "there"])

SyntaxError: invalid syntax (<ipython-input-37-d58cdc29eeca>, line 2)